[build]
  command = "npm run build"
  publish = "public"

[build.environment]
  NODE_VERSION = "18.20.8"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max-old-space-size=4096"
  GATSBY_CLOUD_IMAGE_CDN = "false"
  NETLIFY_IMAGE_CDN = "false"

[[plugins]]
  package = "@netlify/plugin-gatsby"